// resources.js

const resources =
  [
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=190",
    "name":"Mission Bon Accueil - R\u00e9sidences Bon accueil",
    "phone":"514 523-5288",
    "address":"4755A, rue Acorn, Montr\u00e9al (Qu\u00e9bec) H4C 3L6",
    "website":"www.missionbonaccueil.com\/services-fr\/soins-et-soutien\/",
    "services":"R\u00e9insertion sociale en toxicomanie",
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 28 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 180 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Approche de type biopsychosocial (mod\u00e8le Minnesota), approche cognitive et entretien motivationnel",
    "postal_code":"H4C 3L6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=190",
    "name":"Mission Bon Accueil - R\u00e9sidences Bon accueil",
    "phone":"514 523-5288",
    "address":"4755A, rue Acorn, Montr\u00e9al (Qu\u00e9bec) H4C 3L6",
    "website":"www.missionbonaccueil.com\/services-fr\/soins-et-soutien\/",
    "services":null,
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 28 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 180 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Approche de type biopsychosocial (mod\u00e8le Minnesota), approche cognitive et entretien motivationnel",
    "postal_code":"H4C 3L6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=146",
    "name":"Maison L\u2019Exode \u2013 Pavillon Andr\u00e9-Dumont",
    "phone":"514 255-7727",
    "address":"2590, avenue L\u00e9tourneux, Montr\u00e9al (Qu\u00e9bec) H1V 2P4",
    "website":"www.maison-exode.org",
    "services":"R\u00e9insertion sociale en toxicomanie",
    "clientele":null,
    "capacity":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes judiciaris\u00e9es",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacit\u00e9: 20 personnes",
    "approach":"Dur\u00e9e du programme : 90 \u00e0 365 jours",
    "postal_code":"H1V 2P4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=146",
    "name":"Maison L\u2019Exode \u2013 Pavillon Andr\u00e9-Dumont",
    "phone":"514 255-7727",
    "address":"2590, avenue L\u00e9tourneux, Montr\u00e9al (Qu\u00e9bec) H1V 2P4",
    "website":"www.maison-exode.org",
    "services":null,
    "clientele":null,
    "capacity":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes judiciaris\u00e9es",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Capacit\u00e9: 20 personnes",
    "approach":"Dur\u00e9e du programme : 90 \u00e0 365 jours",
    "postal_code":"H1V 2P4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=277",
    "name":"Maison L\u2019Exode \u2013 Pavillon Alpha",
    "phone":"514 508-6900",
    "address":"6400, rue Clark, Montr\u00e9al (Qu\u00e9bec) H2S 3E6",
    "website":"www.maison-exode.org",
    "services":"Aide et soutien \u00e0 la r\u00e9cup\u00e9ration \u00e0 la suite d'une intoxication (d\u00e9grisement)",
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes pr\u00e9sentant \u00e0 la fois une d\u00e9pendance et un trouble de sant\u00e9 mentale",
    "capacity":"Capacit\u00e9: 12 places",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Maximum 3 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : R\u00e9duction des m\u00e9faits",
    "postal_code":"H2S 3E6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=277",
    "name":"Maison L\u2019Exode \u2013 Pavillon Alpha",
    "phone":"514 508-6900",
    "address":"6400, rue Clark, Montr\u00e9al (Qu\u00e9bec) H2S 3E6",
    "website":"www.maison-exode.org",
    "services":null,
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes pr\u00e9sentant \u00e0 la fois une d\u00e9pendance et un trouble de sant\u00e9 mentale",
    "capacity":"Capacit\u00e9: 12 places",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Maximum 3 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : R\u00e9duction des m\u00e9faits",
    "postal_code":"H2S 3E6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=151",
    "name":"Le Grand Chemin (Montr\u00e9al)",
    "phone":"514 381-1218",
    "address":"7070, boulevard Perras, Montr\u00e9al (Qu\u00e9bec) H1E 1A4",
    "website":"www.legrandchemin.qc.ca",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":null,
    "capacity":"Client\u00e8le : Jeunes de 12 \u00e0 17 ans",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacit\u00e9: 12 personnes",
    "approach":"Dur\u00e9e du programme : 56 \u00e0 70 jours",
    "postal_code":"H1E 1A4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=151",
    "name":"Le Grand Chemin (Montr\u00e9al)",
    "phone":"514 381-1218",
    "address":"7070, boulevard Perras, Montr\u00e9al (Qu\u00e9bec) H1E 1A4",
    "website":"www.legrandchemin.qc.ca",
    "services":"Th\u00e9rapie en jeu pathologique",
    "clientele":null,
    "capacity":"Client\u00e8le : Jeunes de 12 \u00e0 17 ans",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacit\u00e9: 12 personnes",
    "approach":"Dur\u00e9e du programme : 56 \u00e0 70 jours",
    "postal_code":"H1E 1A4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=151",
    "name":"Le Grand Chemin (Montr\u00e9al)",
    "phone":"514 381-1218",
    "address":"7070, boulevard Perras, Montr\u00e9al (Qu\u00e9bec) H1E 1A4",
    "website":"www.legrandchemin.qc.ca",
    "services":null,
    "clientele":null,
    "capacity":"Client\u00e8le : Jeunes de 12 \u00e0 17 ans",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Capacit\u00e9: 12 personnes",
    "approach":"Dur\u00e9e du programme : 56 \u00e0 70 jours",
    "postal_code":"H1E 1A4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=63",
    "name":"La Maison Jean Lapointe inc.",
    "phone":"514 288-2611",
    "address":"111, rue Normand, Montr\u00e9al (Qu\u00e9bec) H2Y 2K6",
    "website":"www.maisonjeanlapointe.com",
    "services":"Aide et soutien \u00e0 la d\u00e9sintoxication",
    "clientele":null,
    "capacity":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacit\u00e9: 48 personnes",
    "approach":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 \u00e0 10 jours : Th\u00e9rapie :  21 \u00e0 28 jours",
    "postal_code":"H2Y 2K6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=63",
    "name":"La Maison Jean Lapointe inc.",
    "phone":"514 288-2611",
    "address":"111, rue Normand, Montr\u00e9al (Qu\u00e9bec) H2Y 2K6",
    "website":"www.maisonjeanlapointe.com",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":null,
    "capacity":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacit\u00e9: 48 personnes",
    "approach":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 \u00e0 10 jours : Th\u00e9rapie :  21 \u00e0 28 jours",
    "postal_code":"H2Y 2K6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=63",
    "name":"La Maison Jean Lapointe inc.",
    "phone":"514 288-2611",
    "address":"111, rue Normand, Montr\u00e9al (Qu\u00e9bec) H2Y 2K6",
    "website":"www.maisonjeanlapointe.com",
    "services":"Th\u00e9rapie en jeu pathologique",
    "clientele":null,
    "capacity":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacit\u00e9: 48 personnes",
    "approach":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 \u00e0 10 jours : Th\u00e9rapie :  21 \u00e0 28 jours",
    "postal_code":"H2Y 2K6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=63",
    "name":"La Maison Jean Lapointe inc.",
    "phone":"514 288-2611",
    "address":"111, rue Normand, Montr\u00e9al (Qu\u00e9bec) H2Y 2K6",
    "website":"www.maisonjeanlapointe.com",
    "services":null,
    "clientele":null,
    "capacity":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Capacit\u00e9: 48 personnes",
    "approach":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 \u00e0 10 jours : Th\u00e9rapie :  21 \u00e0 28 jours",
    "postal_code":"H2Y 2K6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=304",
    "name":"La Maison du Pharillon",
    "phone":"514 254-8560",
    "address":"2410, rue Nicolet, Montr\u00e9al (Qu\u00e9bec) H1W 3L4",
    "website":"www.pharillon.org",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es",
    "capacity":"Capacit\u00e9: 20 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 90 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Minnesota (12 \u00e9tapes, cognitivo-comportementale et entretien motivationnel)",
    "postal_code":"H1W 3L4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=304",
    "name":"La Maison du Pharillon",
    "phone":"514 254-8560",
    "address":"2410, rue Nicolet, Montr\u00e9al (Qu\u00e9bec) H1W 3L4",
    "website":"www.pharillon.org",
    "services":null,
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es",
    "capacity":"Capacit\u00e9: 20 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 90 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Minnesota (12 \u00e9tapes, cognitivo-comportementale et entretien motivationnel)",
    "postal_code":"H1W 3L4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=145",
    "name":"L'Escale Notre-Dame",
    "phone":"514 251-0805",
    "address":"1475, avenue Morgan, Montr\u00e9al (Qu\u00e9bec) H1V 2P6",
    "website":"www.escalenotredame.com",
    "services":"R\u00e9insertion sociale en toxicomanie",
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 15 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Th\u00e9rapie :  105 jours : R\u00e9insertion sociale :  365 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Humaniste, cognitivo-comportementale",
    "postal_code":"H1V 2P6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=145",
    "name":"L'Escale Notre-Dame",
    "phone":"514 251-0805",
    "address":"1475, avenue Morgan, Montr\u00e9al (Qu\u00e9bec) H1V 2P6",
    "website":"www.escalenotredame.com",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 15 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Th\u00e9rapie :  105 jours : R\u00e9insertion sociale :  365 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Humaniste, cognitivo-comportementale",
    "postal_code":"H1V 2P6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=145",
    "name":"L'Escale Notre-Dame",
    "phone":"514 251-0805",
    "address":"1475, avenue Morgan, Montr\u00e9al (Qu\u00e9bec) H1V 2P6",
    "website":"www.escalenotredame.com",
    "services":null,
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 15 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Th\u00e9rapie :  105 jours : R\u00e9insertion sociale :  365 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Humaniste, cognitivo-comportementale",
    "postal_code":"H1V 2P6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=217",
    "name":"Centre Toxico-Stop, centre d'h\u00e9bergement offrant de la th\u00e9rapie",
    "phone":"514 327-6017",
    "address":"4858, boulevard Gouin Est, Montr\u00e9al (Qu\u00e9bec) H1G 1A2",
    "website":"toxico-stop.com",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 22 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 21 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Cognitivo-comportementale et pr\u00e9vention de la rechute",
    "postal_code":"H1G 1A2"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=217",
    "name":"Centre Toxico-Stop, centre d'h\u00e9bergement offrant de la th\u00e9rapie",
    "phone":"514 327-6017",
    "address":"4858, boulevard Gouin Est, Montr\u00e9al (Qu\u00e9bec) H1G 1A2",
    "website":"toxico-stop.com",
    "services":null,
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 22 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 21 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Cognitivo-comportementale et pr\u00e9vention de la rechute",
    "postal_code":"H1G 1A2"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=216",
    "name":"Centre Toxico-Stop, centre d'h\u00e9bergement offrant de la r\u00e9insertion sociale",
    "phone":"514 327-6017",
    "address":"4800, boulevard Gouin Est, Montr\u00e9al (Qu\u00e9bec) H1H 1G4",
    "website":"toxico-stop.com",
    "services":"R\u00e9insertion sociale en toxicomanie",
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 17 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 180 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Pyramide de Maslow",
    "postal_code":"H1H 1G4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=216",
    "name":"Centre Toxico-Stop, centre d'h\u00e9bergement offrant de la r\u00e9insertion sociale",
    "phone":"514 327-6017",
    "address":"4800, boulevard Gouin Est, Montr\u00e9al (Qu\u00e9bec) H1H 1G4",
    "website":"toxico-stop.com",
    "services":null,
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution",
    "capacity":"Capacit\u00e9: 17 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 180 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Pyramide de Maslow",
    "postal_code":"H1H 1G4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=203",
    "name":"Centre Booth de Montr\u00e9al",
    "phone":"514 932-2214",
    "address":"880, rue Guy, Montr\u00e9al (Qu\u00e9bec) H3J 1T4",
    "website":"www.centreboothmtl.ca\/ancrage.html",
    "services":"R\u00e9insertion sociale en toxicomanie",
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution, personnes qui pr\u00e9sentent \u00e0 la fois une d\u00e9pendance et un trouble de sant\u00e9 mentale",
    "capacity":"Capacit\u00e9: 45 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Th\u00e9rapie :  180 jours : R\u00e9insertion sociale :  90 \u00e0 360 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Cognitivo-comportementale, communautaire",
    "postal_code":"H3J 1T4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=203",
    "name":"Centre Booth de Montr\u00e9al",
    "phone":"514 932-2214",
    "address":"880, rue Guy, Montr\u00e9al (Qu\u00e9bec) H3J 1T4",
    "website":"www.centreboothmtl.ca\/ancrage.html",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution, personnes qui pr\u00e9sentent \u00e0 la fois une d\u00e9pendance et un trouble de sant\u00e9 mentale",
    "capacity":"Capacit\u00e9: 45 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Th\u00e9rapie :  180 jours : R\u00e9insertion sociale :  90 \u00e0 360 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Cognitivo-comportementale, communautaire",
    "postal_code":"H3J 1T4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=203",
    "name":"Centre Booth de Montr\u00e9al",
    "phone":"514 932-2214",
    "address":"880, rue Guy, Montr\u00e9al (Qu\u00e9bec) H3J 1T4",
    "website":"www.centreboothmtl.ca\/ancrage.html",
    "services":null,
    "clientele":"Client\u00e8le : Hommes (18 ans et plus), personnes judiciaris\u00e9es, personnes en traitement de substitution, personnes qui pr\u00e9sentent \u00e0 la fois une d\u00e9pendance et un trouble de sant\u00e9 mentale",
    "capacity":"Capacit\u00e9: 45 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Th\u00e9rapie :  180 jours : R\u00e9insertion sociale :  90 \u00e0 360 jours",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Cognitivo-comportementale, communautaire",
    "postal_code":"H3J 1T4"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=290",
    "name":"Andy's House Treatment Centre-Centre de Traitement Maison d'Andy",
    "phone":"514 738-2639, sans frais :  1 844 689-2639",
    "address":"3360, rue Notre-Dame, suite 25 Lachine (Qu\u00e9bec) H8T 3E2",
    "website":"www.andyshouse.com",
    "services":"Aide et soutien \u00e0 la d\u00e9sintoxication",
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "capacity":"Capacit\u00e9: 12 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 jours : Th\u00e9rapie :  90 jours ou 35 jours suivi d\u2019un programme intensif de 16 semaines \u00e0 l\u2019externe",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Minnesota 12 \u00e9tapes, syst\u00e9mique, psycho\u00e9ducative, cognitivo-comportementale de r\u00e9solution de probl\u00e8mes, Interpersonnal Process Groups",
    "postal_code":"H8T 3E2"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=290",
    "name":"Andy's House Treatment Centre-Centre de Traitement Maison d'Andy",
    "phone":"514 738-2639, sans frais :  1 844 689-2639",
    "address":"3360, rue Notre-Dame, suite 25 Lachine (Qu\u00e9bec) H8T 3E2",
    "website":"www.andyshouse.com",
    "services":"Th\u00e9rapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "capacity":"Capacit\u00e9: 12 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 jours : Th\u00e9rapie :  90 jours ou 35 jours suivi d\u2019un programme intensif de 16 semaines \u00e0 l\u2019externe",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Minnesota 12 \u00e9tapes, syst\u00e9mique, psycho\u00e9ducative, cognitivo-comportementale de r\u00e9solution de probl\u00e8mes, Interpersonnal Process Groups",
    "postal_code":"H8T 3E2"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=290",
    "name":"Andy's House Treatment Centre-Centre de Traitement Maison d'Andy",
    "phone":"514 738-2639, sans frais :  1 844 689-2639",
    "address":"3360, rue Notre-Dame, suite 25 Lachine (Qu\u00e9bec) H8T 3E2",
    "website":"www.andyshouse.com",
    "services":null,
    "clientele":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "capacity":"Capacit\u00e9: 12 personnes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : Aide et soutien \u00e0 la d\u00e9sintoxication :  7 jours : Th\u00e9rapie :  90 jours ou 35 jours suivi d\u2019un programme intensif de 16 semaines \u00e0 l\u2019externe",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Minnesota 12 \u00e9tapes, syst\u00e9mique, psycho\u00e9ducative, cognitivo-comportementale de r\u00e9solution de probl\u00e8mes, Interpersonnal Process Groups",
    "postal_code":"H8T 3E2"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=289",
    "name":"Clinique Nouveau d\u00e9part",
    "phone":"514 521-9023",
    "address":"1110, avenue Beaumont Ville Mont-Royal (Qu\u00e9bec) H3P 3E5",
    "website":"www.cliniquenouveaudepart.com",
    "services":"Services th\u00e9rapeutiques avec h\u00e9bergement",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "approach":"Capacit\u00e9: 30 places en interne et le service externe, centre de jour",
    "postal_code":"H3P 3E5"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=289",
    "name":"Clinique Nouveau d\u00e9part",
    "phone":"514 521-9023",
    "address":"1110, avenue Beaumont Ville Mont-Royal (Qu\u00e9bec) H3P 3E5",
    "website":"www.cliniquenouveaudepart.com",
    "services":"Service d'aide et de soutien \u00e0 la d\u00e9sintoxication avec h\u00e9bergement",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "approach":"Capacit\u00e9: 30 places en interne et le service externe, centre de jour",
    "postal_code":"H3P 3E5"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=289",
    "name":"Clinique Nouveau d\u00e9part",
    "phone":"514 521-9023",
    "address":"1110, avenue Beaumont Ville Mont-Royal (Qu\u00e9bec) H3P 3E5",
    "website":"www.cliniquenouveaudepart.com",
    "services":"R\u00e9insertion sociale",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "approach":"Capacit\u00e9: 30 places en interne et le service externe, centre de jour",
    "postal_code":"H3P 3E5"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=289",
    "name":"Clinique Nouveau d\u00e9part",
    "phone":"514 521-9023",
    "address":"1110, avenue Beaumont Ville Mont-Royal (Qu\u00e9bec) H3P 3E5",
    "website":"www.cliniquenouveaudepart.com",
    "services":"Aide et soutien \u00e0 l'entourage",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "approach":"Capacit\u00e9: 30 places en interne et le service externe, centre de jour",
    "postal_code":"H3P 3E5"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=289",
    "name":"Clinique Nouveau d\u00e9part",
    "phone":"514 521-9023",
    "address":"1110, avenue Beaumont Ville Mont-Royal (Qu\u00e9bec) H3P 3E5",
    "website":"www.cliniquenouveaudepart.com",
    "services":null,
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Client\u00e8le : Hommes et femmes (18 ans et plus)",
    "approach":"Capacit\u00e9: 30 places en interne et le service externe, centre de jour",
    "postal_code":"H3P 3E5"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=287",
    "name":"Portage TSTM",
    "phone":"514 935-3431",
    "address":"2455, avenue Lionel-Groulx, Montr\u00e9al (Qu\u00e9bec) H3J 1J6",
    "website":"www.portage.ca",
    "services":"R\u00e9insertion sociale",
    "clientele":"Client\u00e8le : Le programme est destin\u00e9 aux hommes souffrant de probl\u00e8mes concomitants de sant\u00e9 mentale (principalement la schizophr\u00e9nie) et de toxicomanie. Il traite les deux conditions ainsi que leurs interactions",
    "capacity":"Capacit\u00e9: 20 hommes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : La dur\u00e9e du programme en r\u00e9sidence est d\u2019environ 6 mois, selon les besoins de l\u2019individu, suivi par une p\u00e9riode de 6 mois \u00e0 2 ans en appartements supervis\u00e9s.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":"H3J 1J6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=287",
    "name":"Portage TSTM",
    "phone":"514 935-3431",
    "address":"2455, avenue Lionel-Groulx, Montr\u00e9al (Qu\u00e9bec) H3J 1J6",
    "website":"www.portage.ca",
    "services":"Programmes de formation \u00e0 l'emploi (au Qu\u00e9bec)",
    "clientele":"Client\u00e8le : Le programme est destin\u00e9 aux hommes souffrant de probl\u00e8mes concomitants de sant\u00e9 mentale (principalement la schizophr\u00e9nie) et de toxicomanie. Il traite les deux conditions ainsi que leurs interactions",
    "capacity":"Capacit\u00e9: 20 hommes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : La dur\u00e9e du programme en r\u00e9sidence est d\u2019environ 6 mois, selon les besoins de l\u2019individu, suivi par une p\u00e9riode de 6 mois \u00e0 2 ans en appartements supervis\u00e9s.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":"H3J 1J6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=287",
    "name":"Portage TSTM",
    "phone":"514 935-3431",
    "address":"2455, avenue Lionel-Groulx, Montr\u00e9al (Qu\u00e9bec) H3J 1J6",
    "website":"www.portage.ca",
    "services":"L'Acad\u00e9mie Portage",
    "clientele":"Client\u00e8le : Le programme est destin\u00e9 aux hommes souffrant de probl\u00e8mes concomitants de sant\u00e9 mentale (principalement la schizophr\u00e9nie) et de toxicomanie. Il traite les deux conditions ainsi que leurs interactions",
    "capacity":"Capacit\u00e9: 20 hommes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : La dur\u00e9e du programme en r\u00e9sidence est d\u2019environ 6 mois, selon les besoins de l\u2019individu, suivi par une p\u00e9riode de 6 mois \u00e0 2 ans en appartements supervis\u00e9s.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":"H3J 1J6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=287",
    "name":"Portage TSTM",
    "phone":"514 935-3431",
    "address":"2455, avenue Lionel-Groulx, Montr\u00e9al (Qu\u00e9bec) H3J 1J6",
    "website":"www.portage.ca",
    "services":"Activit\u00e9s socioculturelles",
    "clientele":"Client\u00e8le : Le programme est destin\u00e9 aux hommes souffrant de probl\u00e8mes concomitants de sant\u00e9 mentale (principalement la schizophr\u00e9nie) et de toxicomanie. Il traite les deux conditions ainsi que leurs interactions",
    "capacity":"Capacit\u00e9: 20 hommes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : La dur\u00e9e du programme en r\u00e9sidence est d\u2019environ 6 mois, selon les besoins de l\u2019individu, suivi par une p\u00e9riode de 6 mois \u00e0 2 ans en appartements supervis\u00e9s.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":"H3J 1J6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=287",
    "name":"Portage TSTM",
    "phone":"514 935-3431",
    "address":"2455, avenue Lionel-Groulx, Montr\u00e9al (Qu\u00e9bec) H3J 1J6",
    "website":"www.portage.ca",
    "services":"Services \u00e0 la famille",
    "clientele":"Client\u00e8le : Le programme est destin\u00e9 aux hommes souffrant de probl\u00e8mes concomitants de sant\u00e9 mentale (principalement la schizophr\u00e9nie) et de toxicomanie. Il traite les deux conditions ainsi que leurs interactions",
    "capacity":"Capacit\u00e9: 20 hommes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : La dur\u00e9e du programme en r\u00e9sidence est d\u2019environ 6 mois, selon les besoins de l\u2019individu, suivi par une p\u00e9riode de 6 mois \u00e0 2 ans en appartements supervis\u00e9s.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":"H3J 1J6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=287",
    "name":"Portage TSTM",
    "phone":"514 935-3431",
    "address":"2455, avenue Lionel-Groulx, Montr\u00e9al (Qu\u00e9bec) H3J 1J6",
    "website":"www.portage.ca",
    "services":null,
    "clientele":"Client\u00e8le : Le programme est destin\u00e9 aux hommes souffrant de probl\u00e8mes concomitants de sant\u00e9 mentale (principalement la schizophr\u00e9nie) et de toxicomanie. Il traite les deux conditions ainsi que leurs interactions",
    "capacity":"Capacit\u00e9: 20 hommes",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : La dur\u00e9e du programme en r\u00e9sidence est d\u2019environ 6 mois, selon les besoins de l\u2019individu, suivi par une p\u00e9riode de 6 mois \u00e0 2 ans en appartements supervis\u00e9s.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":"H3J 1J6"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=286",
    "name":"Portage M\u00e8re-enfant",
    "phone":"514 935-3152",
    "address":"Adresse confidentielle",
    "website":"www.portage.ca",
    "services":"R\u00e9insertion sociale",
    "clientele":"Client\u00e8le : Les m\u00e8res souffrant de probl\u00e8mes de toxicomanie ainsi que leurs enfants \u00e2g\u00e9s de 0 \u00e0 6 ans.",
    "capacity":"Capacit\u00e9: 25 m\u00e8res et 25 enfants",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 6 \u00e0 8 mois selon les besoins de l'individus.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":null
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=286",
    "name":"Portage M\u00e8re-enfant",
    "phone":"514 935-3152",
    "address":"Adresse confidentielle",
    "website":"www.portage.ca",
    "services":"Programmes de formation \u00e0 l'emploi (au Qu\u00e9bec)",
    "clientele":"Client\u00e8le : Les m\u00e8res souffrant de probl\u00e8mes de toxicomanie ainsi que leurs enfants \u00e2g\u00e9s de 0 \u00e0 6 ans.",
    "capacity":"Capacit\u00e9: 25 m\u00e8res et 25 enfants",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 6 \u00e0 8 mois selon les besoins de l'individus.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":null
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=286",
    "name":"Portage M\u00e8re-enfant",
    "phone":"514 935-3152",
    "address":"Adresse confidentielle",
    "website":"www.portage.ca",
    "services":"L'Acad\u00e9mie Portage",
    "clientele":"Client\u00e8le : Les m\u00e8res souffrant de probl\u00e8mes de toxicomanie ainsi que leurs enfants \u00e2g\u00e9s de 0 \u00e0 6 ans.",
    "capacity":"Capacit\u00e9: 25 m\u00e8res et 25 enfants",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 6 \u00e0 8 mois selon les besoins de l'individus.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":null
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=286",
    "name":"Portage M\u00e8re-enfant",
    "phone":"514 935-3152",
    "address":"Adresse confidentielle",
    "website":"www.portage.ca",
    "services":"Activit\u00e9s socioculturelles",
    "clientele":"Client\u00e8le : Les m\u00e8res souffrant de probl\u00e8mes de toxicomanie ainsi que leurs enfants \u00e2g\u00e9s de 0 \u00e0 6 ans.",
    "capacity":"Capacit\u00e9: 25 m\u00e8res et 25 enfants",
    "dependency_category":null,
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 6 \u00e0 8 mois selon les besoins de l'individus.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":null
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=286",
    "name":"Portage M\u00e8re-enfant",
    "phone":"514 935-3152",
    "address":"Adresse confidentielle",
    "website":"www.portage.ca",
    "services":null,
    "clientele":"Client\u00e8le : Les m\u00e8res souffrant de probl\u00e8mes de toxicomanie ainsi que leurs enfants \u00e2g\u00e9s de 0 \u00e0 6 ans.",
    "capacity":"Capacit\u00e9: 25 m\u00e8res et 25 enfants",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Dur\u00e9e du programme : 6 \u00e0 8 mois selon les besoins de l'individus.",
    "approach":"Approche(s) pr\u00e9conis\u00e9e(s) : Communaut\u00e9 th\u00e9rapeutique",
    "postal_code":null
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Services de r\u00e9adaptation en externe et avec h\u00e9bergement",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Services offerts en fran\u00e7ais et en anglais",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"R\u00e9insertion sociale",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Accueil, \u00e9valuation, orientation",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Aide et soutien \u00e0 l'entourage",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Traitements de substitution",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Programmes de formation \u00e0 l'emploi (au Qu\u00e9bec)",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"L'Acad\u00e9mie Portage",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":"Activit\u00e9s socioculturelles",
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":null,
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=65",
    "name":"Portage - Si\u00e8ge social",
    "phone":"514 939-0202",
    "address":"865, place Richmond, Montr\u00e9al (Qu\u00e9bec) H3J 1V8",
    "website":"www.portage.ca",
    "services":null,
    "clientele":"Client\u00e8le : Jeunes et adultes",
    "capacity":"Derni\u00e8re mise \u00e0 jour :  17 juin 2024",
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":null,
    "approach":null,
    "postal_code":"H3J 1V8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Services de r\u00e9adaptation en externe et avec h\u00e9bergement",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"R\u00e9insertion sociale avec h\u00e9bergement",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"R\u00e9insertion sociale",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Accueil, \u00e9valuation, orientation",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Aide et soutien \u00e0 l'entourage",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Services de gestion du sevrage avec h\u00e9bergement",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Programme d'\u00e9valuation du risque de r\u00e9cidive de la conduite avec les capacit\u00e9s affaiblies (PERRCCA)",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":"Professionnels r\u00e9pondants et formations pour les partenaires",
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":null,
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  },
  {
    "data_source":"https: \/\/www.msss.gouv.qc.ca\/repertoires\/dependances\/fiche_public.php?nofiche=57",
    "name":"Centre de r\u00e9adaptation en d\u00e9pendance du CIUSSS du Centre-Sud-de-l\u2019\u00eele-de-Montr\u00e9al",
    "phone":"514 385-1232",
    "address":"950, rue Louvain Est, Montr\u00e9al (Qu\u00e9bec) H2M 2E8",
    "website":"www.dependancemontreal.ca",
    "services":null,
    "clientele":"Pour l'utilisation probl\u00e9matique d\u2019Internet et des \u00e9crans",
    "capacity":null,
    "dependency_category":"Pour les probl\u00e8mes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Client\u00e8le : Jeunes et adultes",
    "approach":"Autres informations:  Les services en lien avec les traitements des troubles li\u00e9s \u00e0 l\u2019utilisation des opio\u00efdes avec une m\u00e9dication de substitution sont offerts en fran\u00e7ais et en anglais.: Les autres services sont offerts en fran\u00e7ais.",
    "postal_code":"H2M 2E8"
  }
]
  ;
