// resources.js

const resources = [
[
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=190",
    "name":"Mission Bon Accueil - Résidences Bon accueil",
    "phone":"514 523-5288",
    "address":"4755A, rue Acorn, Montréal (Québec) H4C 3L6",
    "website":"www.missionbonaccueil.com/services-fr/soins-et-soutien/",
    "services":"Réinsertion sociale en toxicomanie",
    "clientele":"Clientèle : Hommes (18 ans et plus), personnes judiciarisées, personnes en traitement de substitution",
    "capacity":"Capacité: 28 personnes",
    "dependency_category":null,
    "email":null,
    "program_duration":"Durée du programme : 180 jours",
    "approach":"Approche(s) préconisée(s) : Approche de type biopsychosocial (modèle Minnesota), approche cognitive et entretien motivationnel",
    "postal_code":"H4C 3L6",
    "longitude": -73.5789,
    "latitude": 45.4712
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=190",
    "name":"Mission Bon Accueil - Résidences Bon accueil",
    "phone":"514 523-5288",
    "address":"4755A, rue Acorn, Montréal (Québec) H4C 3L6",
    "website":"www.missionbonaccueil.com/services-fr/soins-et-soutien/",
    "services":null,
    "clientele":"Clientèle : Hommes (18 ans et plus), personnes judiciarisées, personnes en traitement de substitution",
    "capacity":"Capacité: 28 personnes",
    "dependency_category":"Pour les problèmes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Durée du programme : 180 jours",
    "approach":"Approche(s) préconisée(s) : Approche de type biopsychosocial (modèle Minnesota), approche cognitive et entretien motivationnel",
    "postal_code":"H4C 3L6",
    "longitude": -73.5789,
    "latitude": 45.4712
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=146",
    "name":"Maison L’Exode – Pavillon André-Dumont",
    "phone":"514 255-7727",
    "address":"2590, avenue Létourneux, Montréal (Québec) H1V 2P4",
    "website":"www.maison-exode.org",
    "services":"Réinsertion sociale en toxicomanie",
    "clientele":null,
    "capacity":"Clientèle : Hommes et femmes (18 ans et plus), personnes judiciarisées",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacité: 20 personnes",
    "approach":"Durée du programme : 90 à 365 jours",
    "postal_code":"H1V 2P4",
    "longitude": -73.5531,
    "latitude": 45.5619
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=146",
    "name":"Maison L’Exode – Pavillon André-Dumont",
    "phone":"514 255-7727",
    "address":"2590, avenue Létourneux, Montréal (Québec) H1V 2P4",
    "website":"www.maison-exode.org",
    "services":null,
    "clientele":null,
    "capacity":"Clientèle : Hommes et femmes (18 ans et plus), personnes judiciarisées",
    "dependency_category":"Pour les problèmes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Capacité: 20 personnes",
    "approach":"Durée du programme : 90 à 365 jours",
    "postal_code":"H1V 2P4",
    "longitude": -73.5531,
    "latitude": 45.5619
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=277",
    "name":"Maison L’Exode – Pavillon Alpha",
    "phone":"514 508-6900",
    "address":"6400, rue Clark, Montréal (Québec) H2S 3E6",
    "website":"www.maison-exode.org",
    "services":"Aide et soutien à la récupération à la suite d'une intoxication (dégrisement)",
    "clientele":"Clientèle : Hommes et femmes (18 ans et plus), personnes présentant à la fois une dépendance et un trouble de santé mentale",
    "capacity":"Capacité: 12 places",
    "dependency_category":null,
    "email":null,
    "program_duration":"Durée du programme : Maximum 3 jours",
    "approach":"Approche(s) préconisée(s) : Réduction des méfaits",
    "postal_code":"H2S 3E6",
    "longitude": -73.6175,
    "latitude": 45.5355
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=277",
    "name":"Maison L’Exode – Pavillon Alpha",
    "phone":"514 508-6900",
    "address":"6400, rue Clark, Montréal (Québec) H2S 3E6",
    "website":"www.maison-exode.org",
    "services":null,
    "clientele":"Clientèle : Hommes et femmes (18 ans et plus), personnes présentant à la fois une dépendance et un trouble de santé mentale",
    "capacity":"Capacité: 12 places",
    "dependency_category":"Pour les problèmes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Durée du programme : Maximum 3 jours",
    "approach":"Approche(s) préconisée(s) : Réduction des méfaits",
    "postal_code":"H2S 3E6",
    "longitude": -73.6175,
    "latitude": 45.5355
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=151",
    "name":"Le Grand Chemin (Montréal)",
    "phone":"514 381-1218",
    "address":"7070, boulevard Perras, Montréal (Québec) H1E 1A4",
    "website":"www.legrandchemin.qc.ca",
    "services":"Thérapie  en toxicomanie (individuelle ou de groupe)",
    "clientele":null,
    "capacity":"Clientèle : Jeunes de 12 à 17 ans",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacité: 12 personnes",
    "approach":"Durée du programme : 56 à 70 jours",
    "postal_code":"H1E 1A4",
    "longitude": -73.6235,
    "latitude": 45.6481
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=151",
    "name":"Le Grand Chemin (Montréal)",
    "phone":"514 381-1218",
    "address":"7070, boulevard Perras, Montréal (Québec) H1E 1A4",
    "website":"www.legrandchemin.qc.ca",
    "services":"Thérapie en jeu pathologique",
    "clientele":null,
    "capacity":"Clientèle : Jeunes de 12 à 17 ans",
    "dependency_category":null,
    "email":null,
    "program_duration":"Capacité: 12 personnes",
    "approach":"Durée du programme : 56 à 70 jours",
    "postal_code":"H1E 1A4",
    "longitude": -73.6235,
    "latitude": 45.6481
  },
  {
    "data_source":"https://www.msss.gouv.qc.ca/repertoires/dependances/fiche_public.php?nofiche=151",
    "name":"Le Grand Chemin (Montréal)",
    "phone":"514 381-1218",
    "address":"7070, boulevard Perras, Montréal (Québec) H1E 1A4",
    "website":"www.legrandchemin.qc.ca",
    "services":null,
    "clientele":null,
    "capacity":"Clientèle : Jeunes de 12 à 17 ans",
    "dependency_category":"Pour les problèmes d'alcoolisme et de toxicomanie",
    "email":null,
    "program_duration":"Cap
 }
];
